name: Update README with Coverage Badge

on:
  push:
    branches:
      - '**'  # Trigger workflow on pushes to all branches

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.13.1'  # Use a single version string

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Karma tests and generate coverage
        run: yarn test:zephyr-ui:coverage

      - name: Generate Coverage Badge
        id: update-readme
        run: |
          # Extract coverage percentage from coverage report
          COVERAGE_PERCENTAGE=$(awk '/statement/ {print $2}' coverage/unit-test/coverage-summary.txt | sed 's/%//')
          BADGE_URL="https://img.shields.io/badge/Coverage-${COVERAGE_PERCENTAGE}%25-brightgreen"
          
          # Update README.md with the new badge URL
          sed -i "s|https://img.shields.io/badge/Coverage-.*%25-.*|$BADGE_URL|g" README.md
          
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update coverage badge"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger npm publish workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type": "publish_package"}' \
            https://api.github.com/repos/${{ github.repository }}/dispatches
